apiVersion: v2
name: port-k8s-exporter
description: Helm chart for Port K8s Exporter - exports Kubernetes resources to Port
type: application
version: 0.1.0
appVersion: "v0.1.9"
maintainers:
  - name: configbug
