# Values for PROD (Producción) environment

replicaCount: 2

image:
  tag: "v0.1.9"
  pullPolicy: IfNotPresent

webhookUrl: "https://ingest.getport.io/REPLACE_WITH_PROD_WEBHOOK_URL"

clusterName: "prod-cluster"

eventListenerType: "WEBHOOK"

resyncInterval: 15

config:
  createMissingRelatedEntities: true
  resources:
    - kind: v1/namespaces
    - kind: v1/nodes
    - kind: apps/v1/deployments
    - kind: apps/v1/daemonsets
    - kind: apps/v1/statefulsets
    - kind: apps/v1/replicasets
    - kind: v1/pods
    - kind: v1/configmaps

namespace:
  create: true

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi
